@startuml login
actor Calon_Anggota #red
Calon_Anggota->login: 1. Membuka menu login
login-->Calon_Anggota: menampilkan inputan no. HP

Calon_Anggota->login: 2. Mengisi no. HP yang terdaftar
login-->Calon_Anggota: mengirim SMS OTP

Calon_Anggota->login: 3. Memasukkan kode OTP
login-->login: verifikasi OTP

alt Jika OTP benar
    autonumber 1 "<b>[000]"
    autonumber resume "<font color=blue><b>Message 0  "
    login-->Calon_Anggota: verifikasi OTP benar
    Calon_Anggota->login: verifikasi lanjutan
    autonumber stop

else Jika OTP salah
   autonumber 3 "<b>[000]"
   autonumber resume "<font color=red><b>Message 0  "
   login-->Calon_Anggota: verifikasi OTP salah
   autonumber stop
end 
login-->login: verifikasi fingerprint

alt jika ada pingerprint
    autonumber 4 "<b>[000]"
    autonumber resume "<font color=blue><b>Message 0  "
    login->Calon_Anggota: meminta persetujuan by fingerprint
    Calon_Anggota->login: 4. melakukan fingerprint
    login-->Calon_Anggota: sukses dan masuk beranda aplikasi
    autonumber stop

else jika tidak ada pingerprint
   autonumber 7 "<b>[000]"
   autonumber resume "<font color=red><b>Message 0  "
   login->Calon_Anggota: pendaftaran gagal, coba ulang kembali
   autonumber stop

end
@enduml
